### ISSUE TITLE
Link to PDF gives 404

### ISSUE THREAD

**Issue by lispstudent** [fniessen/svn-leuven#1]
In the README, link to PDF gives 404:

`Doc: http://liris.cnrs.fr/seminaires/documents/seminaire_tuto_SVN.pdf`

Would it be possible to include it in the repository instead?

**Comment by fniessen** [comment]
I don’t have a local copy and couldn’t find it online either… 😔

Just as a side note, this repository is quite outdated: I no longer use SVN in any of my current projects, whether at home or work—everything is in Git now.

I’ve spent considerable time refining my workflow with Git (see my other repo) and am planning to host a GitBoost workshop in Paris. I’ll be sharing my Git aliases and tips on maximizing efficiency with the command-line interface. Would you be interested in joining?

**Comment by lispstudent** [comment]
Thank you for checking. `svn-leuven` is still valid and works quite well, that's why I was interested in more. We are using subversion and it does not see we'll change for the foreseeable future. Thank you for the invitation thought! 👍🏻
